const countriesArray = [
  ["Afghanistan"],
  ["Albania"],
  ["Algeria"],
  ["Andorra"],
  ["Angola"],
  ["Antigua & Barbuda"],
  ["Argentina"],
  ["Armenia"],
  ["Australia"],
  ["Austria"],
  ["Azerbaijan"],
  ["Bahamas"],
  ["Bahrain"],
  ["Bangladesh"],
  ["Barbados"],
  ["Belarus"],
  ["Belgium"],
  ["Belize"],
  ["Benin"],
  ["Bhutan"],
  ["Bolivia"],
  ["Bosnia & Herzegovina"],
  ["Botswana"],
  ["Brazil"],
  ["Brunei"],
  ["Bulgaria"],
  ["Burkina Faso"],
  ["Burundi"],
  ["Cambodia"],
  ["Cameroon"],
  ["Canada"],
  ["Cape Verde"],
  ["Central African Republic"],
  ["Chad"],
  ["Chile"],
  ["China"],
  ["Colombia"],
  ["Comoros"],
  ["Congo, Democratic Republic of (DRC)"],
  ["Congo, Republic of the"],
  ["Costa Rica"],
  ["Croatia"],
  ["Cuba"],
  ["Cyprus"],
  ["Czech Republic"],
  ["Denmark"],
  ["Djibouti"],
  ["Dominica"],
  ["Dominican Republic"],
  ["Ecuador"],
  ["Egypt"],
  ["Equatorial Guinea"],
  ["Eritrea"],
  ["Estonia"],
  ["Eswatini (Suaziland)"],
  ["Ethiopia"],
  ["Fiji"],
  ["Finland"],
  ["France"],
  ["Gabon"],
  ["Gambia, Republic of The"],
  ["Georgia"],
  ["Germany"],
  ["Ghana"],
  ["Greece"],
  ["Grenada"],
  ["Guatemala"],
  ["Guinea"],
  ["Guinea-Bissau"],
  ["Guyana"],
  ["Haiti"],
  ["Honduras"],
  ["Hungary"],
  ["Iceland"],
  ["India"],
  ["Indonesia"],
  ["Iran"],
  ["Iraq"],
  ["Ireland"],
  ["Israel"],
  ["Italy"],
  ["Ivory Coast (Cote d'Ivoire)"],
  ["Jamaica"],
  ["Japan"],
  ["Jordan"],
  ["Kazakhstan"],
  ["Kenya"],
  ["Kiribati"],
  ["Korea, Democratic Republic of (North Korea)"],
  ["Korea, Republic of (South Korea)"],
  ["Kosovo"],
  ["Kuwait"],
  ["Kyrgyz Republic (Kyrgyzstan)"],
  ["Laos"],
  ["Latvia"],
  ["Lebanon"],
  ["Lesotho"],
  ["Liberia"],
  ["Libya"],
  ["Liechtenstein"],
  ["Lithuania"],
  ["Luxembourg"],
  ["Madagascar"],
  ["Malawi"],
  ["Malaysia"],
  ["Maldives"],
  ["Mali"],
  ["Malta"],
  ["Marshall Islands"],
  ["Mauritania"],
  ["Mauritius"],
  ["Mexico"],
  ["Micronesia, Federated States of"],
  ["Moldova, Republic of"],
  ["Monaco"],
  ["Mongolia"],
  ["Montenegro"],
  ["Morocco"],
  ["Mozambique"],
  ["Myanmar (Burma)"],
  ["Namibia"],
  ["Nauru"],
  ["Nepal"],
  ["Netherlands"],
  ["New Zealand"],
  ["Nicaragua"],
  ["Niger"],
  ["Nigeria"],
  ["Niue"],
  ["North Macedonia, Republic of"],
  ["Norway"],
  ["Oman"],
  ["Pakistan"],
  ["Palau"],
  ["Palestinian territories (Gaza and the West Bank)"],
  ["Panama"],
  ["Papua New Guinea"],
  ["Paraguay"],
  ["Peru"],
  ["Philippines"],
  ["Poland"],
  ["Portugal"],
  ["Puerto Rico"],
  ["Qatar"],
  ["Romania"],
  ["Russian Federation"],
  ["Rwanda"],
  ["Saint Kitts and Nevis"],
  ["Saint Lucia"],
  ["Saint Vincent and the Grenadines"],
  ["Salvador, El"],
  ["Samoa"],
  ["San Marino"],
  ["Sao Tome and Principe"],
  ["Saudi Arabia"],
  ["Senegal"],
  ["Serbia"],
  ["Seychelles"],
  ["Sierra Leone"],
  ["Singapore"],
  ["Slovak Republic (Slovakia)"],
  ["Slovenia"],
  ["Solomon Islands"],
  ["Somalia"],
  ["South Africa"],
  ["South Sudan"],
  ["Spain"],
  ["Sri Lanka"],
  ["Sudan"],
  ["Suriname"],
  ["Sweden"],
  ["Switzerland"],
  ["Syria"],
  ["Taiwan"],
  ["Tajikistan"],
  ["Tanzania"],
  ["Thailand"],
  ["Timor-Leste"],
  ["Togo"],
  ["Tonga"],
  ["Trinidad & Tobago"],
  ["Tunisia"],
  ["Turkey"],
  ["Turkmenistan"],
  ["Tuvalu"],
  ["Uganda"],
  ["Ukraine"],
  ["United Arab Emirates"],
  ["United Kingdom"],
  ["United States of America (USA)"],
  ["Uruguay"],
  ["Uzbekistan"],
  ["Vanuatu"],
  ["Vatican City"],
  ["Venezuela"],
  ["Vietnam"],
  ["Yemen"],
  ["Zambia"],
  ["Zimbabwe"],
].flat();

export default countriesArray;
